### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by Artymort** [ellisk42/ec#1]
From commit 469f8459 (I think), now I get a `KeyError` error somewhere.

```python
ec/ec.py", line 226, in ecIterator
    }[likelihoodModel]()
KeyError: <likelihoodModel.AllOrNothingLikelihoodModel instance at 0x7f5ce4644b90>
```

* Branch geometry
* `useRecognitionModel=False`
* `compressor="pypy"`

**Comment by lucasem** [comment]
On what ref is this happening? It works for me on 61d0a9b56f81f63ea92df475110248df9f2cc0c6 (geometry) and 074ae769fc1bd3d97698e249737301278b3326d0 (master).

**Comment by Artymort** [comment]
Currently on fda47da41d681c4daa6b9c776c5b20999736f0d9 (just merged master and pushed to be up to date), with a single image in the data/geom folder (e.g. [001_horizontal_l](https://user-images.githubusercontent.com/7687623/37807523-47721ff2-2e1c-11e8-85fa-e76afb8b71f0.png) which is actually one I want to use) I get the reported error.

Output of `python geom.py -t 1` [attached](https://github.com/ellisk42/ec/files/1839843/error.log).

**Comment by lucasem** [comment]
Oh whoops, I see the issue. Give me a couple of minutes..

**Comment by lucasem** [comment]
Another merge should now resolve it — sorry about that!

**Comment by Artymort** [comment]
Fix merged. Thanks!
