### ISSUE TITLE
Running a basic example: solver missing

### ISSUE THREAD

**Issue by gergia** [ellisk42/ec#68]
Hi,

I read the paper and was very happy about ideas and results in it. Thanks for the great work!

I tried to run the basic example, as provided in README. (`python bin/text.py -t 20 -RS 5000`, inside singularity).
Unfortunately, if fails as it cannot find the solver file, as specified by the variable `solver_file`, in the `try` block at line 298 of `enumeration.py` . The solver file is specified to be called `solver`, inside the root directory. However, that file does not exist.

What am I missing? At what point should the solver file be created?

NOTE: 
The original README command was `python text.py -t 20 -RS 5000` (without `bin` part), but I assume this was a typo. I also tried moving to the `bin` folder and executing the original command, but that failed as it seems to assume the execution from the root directory.

**Comment by gergia** [comment]
@jrb314 , I see that you were (successfully) running the code [back in July](https://github.com/ellisk42/ec/issues/64), could you share if you had similar problems and how did you resolve them?

**Comment by Sharad24** [comment]
I got this error too when I was running on my local laptop. Did not get the error when I ran the same on a higher memory machine.

**Comment by jrb314** [comment]
@gergia, I did not run inside singularity.  From the ec folder, i ran
python bin/list.py
But first, had to install these 2 libs:
apt-get install libzmq3-dev
apt-get install libcairo2

**Comment by ellisk42** [comment]
@gergia the solver binary should be part of the repo (compiled for Linux). You can also try building it if you don't see it, by running `make clean; make` (I recommend building using the container, ie doing `./container.img` and then running the build commands). By default the container will mount your home directory, so it will have access to files if and only if they are somewhere in your home directory (or, recursively, a subdirectory of your home directory). Are you doing stuff in the container which is not a subdirectory of your home directory?

**Comment by gergia** [comment]
Thanks everybody for your help. 
It seems that the problem was the user, not the system. Let me give the explanation here in case somebody faces a similar issue: what probably happened is that I tried to compile outside of singularity, which failed. Thus, the `solver` file was deleted. Since I had a "virtual machine" model of what singularity is, I did not understand that all the files are shared (so the file was missing inside singularity as well).

@ellisk42 : I ended up downloading the compiled version from the repo to try out the system. (I failed to compile even inside singularity. I will investigate this problem in more detail and then, if necessary, open another issue.)

**Comment by sneiman** [comment]
> @gergia the solver binary should be part of the repo (compiled for Linux). You can also try building it if you don't see it, by running `make clean; make` (I recommend building using the container, ie doing `./container.img` and then running the build commands). By default the container will mount your home directory, so it will have access to files if and only if they are somewhere in your home directory (or, recursively, a subdirectory of your home directory). Are you doing stuff in the container which is not a subdirectory of your home directory?

@ellisk42 Sorry to bother you - I am having a related problem. Just cannot get the system to build the ocaml libs. I describe the problem in detail in issue #96. And singularity wont build. and help much appreciated
