### ISSUE TITLE
Question: How does the concept abstraction algorithm work?

### ISSUE THREAD

**Issue by slightknack** [ellisk42/ec#73]
Hey, I read through the technical paper, but I don't see a whole lot of information as to the refactoring algorithm over lambda terms works. I'm fluent in Rust, and it looks like the `rust_compressor` crate is a good place to start, but I was wondering if there exists a high-level overview of either the crate specifically or the methodology used in general. Thanks!

**Comment by Sharad24** [comment]
The [supplementary work](https://web.mit.edu/ellisk/www/documents/dreamcoder_with_supplement.pdf) has some information, I think.

**Comment by slightknack** [comment]
Alright, I'll take a look at it and let y'all know if I have any further questions.

**Comment by slightknack** [comment]
(Link is dead, here's an archive fwiw: https://web.archive.org/web/20201120133418/https://web.mit.edu/ellisk/www/documents/dreamcoder_with_supplement.pdf)
